# Generated by Django 6.0.3 on 2026-03-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('rf_signal', models.FloatField()),
                ('acoustic_freq', models.FloatField()),
                ('seismic_vib', models.FloatField()),
                ('object_mass', models.FloatField()),
            ],
        ),
    ]
