# Generated by Django 6.0.3 on 2026-04-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fogedgedashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dropped_count', models.IntegerField(default=0)),
            ],
        ),
    ]
